pipeline {
    agent any
    tools {
        maven 'maven1'  // Ensure 'maven1' is properly set up in Jenkins tools configuration
    }
    
    stages {
        stage('Compile and Clean') { 
            steps {
                dir('ftohbackend') {  // Ensure correct directory path, 'ftohbackend' should be quoted
                    sh 'mvn compile'
                }
            }
        }
       
        stage('Junit5 Test') { 
            steps {
                dir('ftohbackend') {  // Ensure correct directory path
                    sh 'mvn test'
                }
            }
        }

        stage('Jacoco Coverage Report') {
            steps {
                // If Jacoco is used, include relevant steps here
                echo 'TestCoverage'
            }
        }

        stage('SonarQube') {
            steps {
                // You can configure SonarQube scanning here
                echo 'Sonar Code Scanning'
            }
        }

        stage('Maven Build') { 
            steps {
                dir('ftohbackend') {  // Ensure correct directory path
                    sh 'mvn clean install'  // 'sh' is used because it's likely a Unix-based agent
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('ftohbackend') {  // Ensure correct directory path
                    sh 'docker build -t villagecart --build-arg VER=1.0 .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                echo "docker login from console"
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker push KHarshaVardhanC/villagecart'  // Using 'sh' for Unix-based systems
            }
        }

        stage('Docker deploy') {
            steps {
                sh 'docker run -itd -p 8080:8080 villagecart'
            }
        }
    }
}
